//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Enrolments = new HashSet<Enrolment>();
        }
    
        public int ClassID { get; set; }
        public Nullable<int> Level { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Enrolment> Enrolments { get; set; }
    }
}
